// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzo3RMW-xyQ9uK-cYhANeZrcHy_9Ji1VQ',
    appId: '1:562995348940:web:ac8314f43d84983a33c969',
    messagingSenderId: '562995348940',
    projectId: 'party-7a1eb',
    authDomain: 'party-7a1eb.firebaseapp.com',
    databaseURL: 'https://party-7a1eb.firebaseio.com',
    storageBucket: 'party-7a1eb.appspot.com',
    measurementId: 'G-EGYLCXJERT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIkmTZwYoYu1rWCw4IaTHxLP1W5IIi3aQ',
    appId: '1:562995348940:android:06b048ab28a8dcba33c969',
    messagingSenderId: '562995348940',
    projectId: 'party-7a1eb',
    databaseURL: 'https://party-7a1eb.firebaseio.com',
    storageBucket: 'party-7a1eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAszggD9aniPLfT-6Izmt_QMKpkPfQqzT4',
    appId: '1:562995348940:ios:f45c8f92311ef6e433c969',
    messagingSenderId: '562995348940',
    projectId: 'party-7a1eb',
    databaseURL: 'https://party-7a1eb.firebaseio.com',
    storageBucket: 'party-7a1eb.appspot.com',
    androidClientId: '562995348940-0qqkerioflq83156dof992datdv6mj92.apps.googleusercontent.com',
    iosClientId: '562995348940-9jbl927cbrpbltipur4u1n9dtioce2dc.apps.googleusercontent.com',
    iosBundleId: 'com.myles.jerm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAszggD9aniPLfT-6Izmt_QMKpkPfQqzT4',
    appId: '1:562995348940:ios:f45c8f92311ef6e433c969',
    messagingSenderId: '562995348940',
    projectId: 'party-7a1eb',
    databaseURL: 'https://party-7a1eb.firebaseio.com',
    storageBucket: 'party-7a1eb.appspot.com',
    androidClientId: '562995348940-0qqkerioflq83156dof992datdv6mj92.apps.googleusercontent.com',
    iosClientId: '562995348940-9jbl927cbrpbltipur4u1n9dtioce2dc.apps.googleusercontent.com',
    iosBundleId: 'com.myles.jerm',
  );
}
